message: Greetings from the PRODUCT-QUERY-SIDE microservice [using the CONFIG SERVICE config].

security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints

spring:
  jpa:
    hibernate:
      ddl-auto: update

query:
  exchange: product.events.exchange
  queue: materialised.view.stream
  terminal: product.axon.terminal

logging:
  level:
    io:
      benwilcock: DEBUG