message: Greetings from the PRODUCT-QUERY-SIDE microservice [using the CONFIG SERVICE config].

security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints

spring:
  application:
    exchange: product.events.fanout.exchange
    queue: event.stream
    terminal: product.axon.terminal
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    io:
      benwilcock: DEBUG